### ISSUE TITLE
Contributors discussion

### ISSUE THREAD

**Issue by dlh2** [friedPotat0/Spam-Scores#37]
I don't know how we should contact between us so I make this "issue"

### Roadmap

- [ ] Fix current Issues
- [ ] Code optimization
- [ ] Add the enhancements/features

### Suggestions by contributors

- [ ] dlh2: Spam auto-delete (As Thunderbird doesn't support compare filters)
